### ISSUE TITLE
Frontend anbinden

### ISSUE THREAD

**Issue by maxomnia** [maxomnia/pm_project_rapla#44]
Requests an die API aus #30 
- [x] Termin hinzufügen
- [x] Termin bearbeiten
- [x] Termin löschen
- [x] Zuverlässiger Darkmode
- [x] Benutzerdaten selbst ändern
- [x] eigene Gruppen statt Standard "TINF21B1" nehmen

**Comment by maxomnia** [comment]
# Bitte bis Mittwoch erledigen

**Comment by Tacconinja007** [comment]
- [ ] Termin hinzufügen
- [ ] Termin bearbeiten
- [ ] Termin löschen
- [ ] Zuverlässiger Darkmode
- [ ] Benutzerdaten selbst ändern
- [ ] eigene Gruppen statt Standard "TINF21B1" nehmen

**Comment by Tacconinja007** [comment]
Klasse! Wir liegen im Zeitplan.
