### ISSUE TITLE
Admin UI erstellen

### ISSUE THREAD

**Issue by maxomnia** [maxomnia/pm_project_rapla#86]
Funktionalität:

- [x] Benutzer zu Gruppen hinzufügen können
- [x] Benutzer Adminrechte geben
- [x] Neue Gruppen erstellen
- [x] Gruppe mit oder ohne Rapla Anbindung, d.h. das Attribut `url` soll leer oder nicht sein

Edit:
- [x] Benutzer löschen
- [x] Benutzerkennwort ändern --> wontfix
- [x] Benutzer aus Gruppen löschen können
- [x] Benutzer aus **allen** Gruppen löschen können
- [x] Benutzer-Gruppen-Management zuverlässig und fehlerfrei

**Comment by Tacconinja007** [comment]
Gruppenverwaltung
![grafik](https://user-images.githubusercontent.com/59054004/178300467-d1110015-d974-49e1-9a8a-9cc8aabaa8ae.png)

- Gruppen (ggf. mit URL) hinzufügen
- Gruppen ansehen (automatisches Laden, Verarbeitung mit JS, **kein XSLT**)

**Comment by maxomnia** [comment]
Das sieht ja super aus 👍

**Comment by Tacconinja007** [comment]
Benutzermanagement
![grafik](https://user-images.githubusercontent.com/59054004/179411152-25b50e07-ac86-4234-9036-b09878895599.png)
