### ISSUE TITLE
Dark Mode Design umsetzen

### ISSUE THREAD

**Issue by maxomnia** [maxomnia/pm_project_rapla#87]

**Comment by Tacconinja007** [comment]
Wie setzen wir den Dark Mode um?

**Variante 1:** Im Browser festlegen
Wer sucht bitte da oben nach Stylesheets??
![grafik](https://user-images.githubusercontent.com/59054004/178158216-12a0949b-b635-4b79-9e0f-03dcdb48f938.png)

**Variante 2:** Input checkbox
Ich habe keine Möglichkeit gefunden, das Event abzufangen, wenn im Browser ein Stylesheet wie in Variante 1 geändert wird.
Die Checkbox zeigt dann die falsche Einstellung an.
Diese Variante ist, davon abgesehen, wesentlich benutzerfreundlicher.
![grafik](https://user-images.githubusercontent.com/59054004/178158359-c5ca53c9-6dc4-4b20-ae70-b78823953be8.png)

**Comment by Tacconinja007** [comment]
Umsetzung von Variante 2 in a1a5b201a5943c9a547dd30cd0191194eb7183e7 und 37267fe6c9c0996a668d5b951d0530715de25799
`rel="alternate stylesheet"` wurde zu `rel="stylesheet" disabled="disabled"` geändert, da nur so Änderung mit JS möglich ist
